//-----------------------------------------------------------------------
// <copyright file="AsyncEventHandler.cs" company="P.O.S Informatique">
//     Copyright (c) P.O.S Informatique. All rights reserved.
// </copyright>
//-----------------------------------------------------------------------

namespace PosInformatique.Azure.Communication.UI.Blazor
{
    /// <summary>
    /// Represents the method that will handle asynchronously an event when the event provides data.
    /// </summary>
    /// <typeparam name="TEvent">The type of the event data generated by the event.</typeparam>
    /// <param name="event">An object that contains the event data.</param>
    /// <returns>A <see cref="Task"/> which represents the asynchronous operation.</returns>
    public delegate Task AsyncEventHandler<TEvent>(TEvent @event);
}
